application: iiumschedule
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /static
  static_dir: static

- url: /
  script: main.application
  secure: optional
  
- url: /scheduleformatter/
  script: scheduleformatter.application
  secure: optional