application: iiumschedule
version: 3
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /static
  static_dir: static
  secure: optional
  
- url: /cleanschedule
  script: scheduleformatter.application
  secure: optional
  login: admin
  
- url: /scheduleformatter/
  script: scheduleformatter.application
  secure: optional
  
- url: /themegallery
  script: scheduleformatter.application
  secure: optional