application: iiumschedule
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /static
  static_dir: static
  
- url: /cleanschedule
  script: scheduleformatter.application
  secure: optional
  login: admin
  
- url: /scheduleformatter/
  script: scheduleformatter.application
  secure: optional