application: iiumschedule
version: 3
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- deferred: on

libraries:
- name: PIL
  version: "1.1.7"
- name: jinja2
  version: 2.6

handlers:

- url: /static
  static_dir: static
  secure: optional
  
- url: /cleanschedule
  script: admincontroller.app
  secure: optional
  login: admin
  
- url: /error
  script: scheduleformatter.application
  secure: optional
  
- url: /scheduleformatter/
  script: scheduleformatter.application
  secure: optional
  
- url: /scheduleloader/?
  script: scheduleformatter.application
  secure: optional
  
- url: /screenshot
  script: themehandler.application
  secure: optional

- url: /admin/?.*
  script: admincontroller.app
  secure: optional
  login: admin
  
- url: /defaultdata 
  script: themehandler.application
  secure: optional

- url: /themegallery
  script: themehandler.application
  secure: optional
  
- url: /favicon.ico
  static_files: static/logo-small.ico
  upload: static/logo-small.ico
  
- url: /
  script: scheduleformatter.application
  secure: optional
